### ISSUE TITLE
Move to Cedaro organization

### ISSUE THREAD

**Issue by bradyvercher** [cedaro/grunt-wp-i18n#50]
I'll be looking into moving this repo over to the @cedaro organization soon to help keep things organized and aid in discoverability (we'll be more active over there).

GitHub should take care of any redirects automatically and nobody should need to make any changes unless it's to update bookmarks. Nevertheless, let me know if you have any questions or concerns.

**Comment by GaryJones** [comment]
Will the npmjs reference (for our package,json files) change?

**Comment by bradyvercher** [comment]
Nope, it'll still be `grunt-wp-i18n`, which is the package identifier in the npm registry. Anything referencing the the GitHub repo URL should be redirected automatically.
