### ISSUE TITLE
Change constructors

### ISSUE THREAD

**Issue by andreg** [cedaro/grunt-wp-i18n#58]
Just a warning today, might be an issue in the future, as per a PHP warning message, methods with the same name as their class will not be constructors in a future version of PHP; there are a bunch of these here and there, and they should probably be converted to `__construct` instead.

Keep it up!

**Comment by bradyvercher** [comment]
Good idea, @andreg! Would you be interested in submitting a PR for this?

**Comment by andreg** [comment]
Absolutely!

**Comment by bradyvercher** [comment]
Fixed in #59
