### ISSUE TITLE
Extract core into a standalone node module

### ISSUE THREAD

**Issue by bradyvercher** [cedaro/grunt-wp-i18n#61]
Awhile back, I researched the possibility to remove the PHP CLI dependency to allow grunt-wp-i18n to run anywhere node can run, but didn't come across anything super promising. While researching that, I started thinking about extracting the core code into a separate package and turning this module into a simple Grunt wrapper.

This would allow for creating plugins for other task runners like Gulp or incorporating the functionality into other modules that don't use Grunt.

I'm also considering adding a basic CLI utility to the node module so it could be installed globally and run in a plugin or theme directory without having to install and configure Grunt for every project.

The tests should ensure the Grunt interface continues working without any issues. The one thing I'm planning to remove is the ability to pass in a custom path for the PHP tools to make maintenance and new features easier to add. A GitHub search didn't turn up any projects that were actually using it.

I've made a bit of progress on the node module already, but figured I'd open this up for discussion in case anyone has any thoughts or concerns.

**Comment by GaryJones** [comment]
Nothing insightful to add from me, other than +1 to splitting it up into functionality + Grunt instigator.

**Comment by bradyvercher** [comment]
I finally got some tests added to the [node module](https://github.com/cedaro/node-wp-i18n) and the tests here continue to pass without any API changes aside from removing the option for a custom tools path.

The plan from here is to merge the `extract-core` branch and release 1.0.0 for both modules.

**Comment by bradyvercher** [comment]
Version 1.0.0 has been released.
