### ISSUE TITLE
Disabling potComments

### ISSUE THREAD

**Issue by corvannoorloos** [cedaro/grunt-wp-i18n#62]
Hello,

Trying to disable/remove the copyright notice at the beginning of the .pot file, can someone tell if there's a better alternative to the following?
```javascript
makepot: {
	target: {
		options: {
			potComments: ' '
		}
	}
}
```
Note the needed space between `' '`.

I've tried setting it to `''`. And false, which displays the following error:
> Fatal error: o.potComments.replace is not a function

**Comment by bradyvercher** [comment]
You should be able to do that using the `processPot` callback. I haven't tested, but something like this might work:

```js
makepot: {
    target: {
        options: {
            processPot: function( pot ) {
                pot.translations[''][''].comments.translator = '';
                return pot;
            }
        }
    }
}
```

**Comment by corvannoorloos** [comment]
I don't know why I didn't think of this. Thanks!
