### ISSUE TITLE
"updateTimestamp: false" is not working properly

### ISSUE THREAD

**Issue by rahulnever2far** [cedaro/grunt-wp-i18n#68]
First of thank you such an awesome plugin :+1: 

There is just one little thing that bugs me. POT-Creation-Date is updated every time even if there are no changes. This is a bit annoying in a version controlled environment, where you don't want to see unnecessary changes.

**Edit:** Just found `updateTimestamp` in the documentations. I think it is exactly what I'm looking for. But when I tried it, it stops updating `POT-Creation-Date`, altogether even if there changes in the translation strings.

**Comment by brianhogg** [comment]
I have the issue where `updateTimestamp: false` in the Gruntfile is just ignored, and the timestamp is updated every time even if no strings have changed.

**Comment by GaryJones** [comment]
FWIW, this is applied [here](https://github.com/cedaro/node-wp-i18n/blob/134b960ab88913302887ac1b8ff193d481a718b6/lib/makepot.js#L91-L94).

**Comment by bradyvercher** [comment]
There [has been a test](https://github.com/cedaro/grunt-wp-i18n/blob/674cf2fdd60bbf7ffce37e1abc46a06c91f0bde3/test/makepot_test.js#L226-L235) for the `updateTimestamp` option for quite awhile and the underlying [node module has its own tests](https://github.com/cedaro/node-wp-i18n/blob/ac4810755b725bb421a521fb34fde0e56dcc065d/test/makepot.js#L35-L51).

My only guess is that this was an issue with an earlier version, but if anyone is still having an issue, please feel free to reopen with more information -- a failing test would be even better.
