### ISSUE TITLE
update node-wp-i18n to v1.0.5

### ISSUE THREAD

**Issue by saas786** [cedaro/grunt-wp-i18n#75]
Hi @bradyvercher 

I was using grunt-wp-i18n on php 7.2, and it was throwing deprecated errors for "create_function", after I did some troubleshooting, it seems like you have fixed it in https://github.com/cedaro/node-wp-i18n/commit/649265d7913bfe4b38ed60a1a38b05f023373abf

but you haven't update your grunt-wp-i18n to use this newer version, also please bump up the version of grunt-wp-i18n so I can update it.

thanks

**Comment by bradyvercher** [comment]
Thanks for the nudge, @saas786. I released [v1.0.2](https://github.com/cedaro/grunt-wp-i18n/releases/tag/v1.0.2) to take care of this.
