### ISSUE TITLE
updateTimestamp: false not working

### ISSUE THREAD

**Issue by themenow** [cedaro/grunt-wp-i18n#76]
Still the date is updated without other changes, I'm using the latest version 1.0.2

```
makepot: {
    theme: {
        options: {
            cwd: '',
            mainFile: 'style.css',
            domainPath: 'languages/',
            exclude: ['node_modules/.*'],
            potFilename: '<%= x %>.pot',
            potHeaders: { 'report-msgid-bugs-to': 'http://theme-homepage' },
            type: 'wp-theme',
            updateTimestamp: false,
        }
    }
};
```

By the way, do I need to add also '.svn' to **exclude** ?

**Comment by bradyvercher** [comment]
I haven't had time to look into this, but [there is a passing test](https://github.com/cedaro/grunt-wp-i18n/blob/develop/test/makepot_test.js#L212-L236) for this . If anyone can demonstrate this behavior with a failing test, that would be helpful.

**Comment by av3nger** [comment]
**updateTimestamp: false** regenerates the .pot file for me as well with only the changed timestamp

```
diff --git a/languages/default.pot b/languages/default.pot
index ea5f43f1..7e9ad854 100644
--- a/languages/default.pot
+++ b/languages/default.pot
@@ -4,7 +4,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: Project Name\n"
-"POT-Creation-Date: 2018-12-19 10:38:42+00:00\n"
+"POT-Creation-Date: 2018-12-19 10:39:15+00:00\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=utf-8\n"
 "Content-Transfer-Encoding: 8bit\n"

```

**Comment by av3nger** [comment]
@bradyvercher , I don't know if this helps, but it's failing at **Pot.prototype.sameAs()**
the **pot.content** contains **X-Generator: grunt-wp-i18n1.0.2** which **this.contents** does not contain. thus the hashes for the files do not match

**Comment by bradyvercher** [comment]
Thanks, but that doesn't really give me any ideas. Is there a reason you know of that would cause the generated POT to be missing the `X-Generator` header?

The Grunt tasks [adds that header](https://github.com/cedaro/grunt-wp-i18n/blob/131e915e43e3e24c4122382f3fd168b3fb235c65/tasks/makepot.js#L44) to the options, then sends those along to the node package. The node package reads the existing POT file, generates a new one, then compares the original with the generated version to see if there have been any changes. The `X-Generator` header should be in both versions.

**Comment by av3nger** [comment]
@bradyvercher, you can configure a separate test task, run it with grunt and compare **pot.content** and **this.contents** - they do not match. X-Generator is present in the headers of both outputs, but it's not there in msgstr section in one of the files

**Comment by bradyvercher** [comment]
@av3nger Ah, thanks for sticking with me on that. I think I figured out what was going on and hopefully [this commit](https://github.com/cedaro/node-wp-i18n/commit/b30a50ac9d72c48d678e410a29509485edfff2a5) should take care of it.

**Comment by bradyvercher** [comment]
I believe this should be good to go in 1.0.3. Feel free to reopen with more details if it still doesn't work.
