### ISSUE TITLE
POT File by text domain

### ISSUE THREAD

**Issue by wayheming** [cedaro/grunt-wp-i18n#79]
Hello, if I have a few text domain in the WordPress Theme, can I specify only the required one and will be generated by skipping not specified?

**Comment by bradyvercher** [comment]
It's not possible to exclude strings by text domain, but you can configure which files are included or excluded from the scan. Ideally your project shouldn't be mixing multiple domains in the same file. See #64 for more discussion.

**Comment by wayheming** [comment]
OK, thanks for your reply =)
