### ISSUE TITLE
Duplicate text domains added where text domain already exists

### ISSUE THREAD

**Issue by helgatheviking** [cedaro/grunt-wp-i18n#86]
My grunt task looks like:

```
addtextdomain: {
			options: {
				textdomain: '<%= pkg.name %>'    // Project text domain.
			},
			target: {
				files: {
					src: ['*.php', '**/*.php', '**/**/*.php', '!node_modules/**', '!deploy/**']
				}
			}
		},
```

where the package.json name is

```
"name": "wc-mnm-grouped",
```

```
 <?php esc_html_e( 'No related Mix and Match products', 'wc-grouped-mnm' ); ?>
```

gets turned into 

```
 <?php esc_html_e( 'No related Mix and Match products', 'wc-grouped-mnm', 'wc-mnm-grouped' ); ?>
```

I can't quite tell if this is a bug or a human error on my part, but how can I stop getting the 2nd text domain from being added where it already exists?

**Comment by bradyvercher** [comment]
Hi @helgatheviking, it's been awhile, so I'd have to dig in to see why a second text domain would be added when one already exists, but it looks like the two don't quite match (`wc-grouped-mnm` vs `wc-mnm-grouped`). Could that be the root of the issue? If so, you might look into the [updateDomains](https://github.com/cedaro/grunt-wp-i18n/blob/130e10b3603cb35bdc7b4b63d7e2d3462a030552/docs/addtextdomain.md#optionsupdatedomains) option.

**Comment by helgatheviking** [comment]
Well I feel silly. But you look at something long enough and it all starts to look the same. Thanks so much for catching that! that was indeed the source of the problem.

**Comment by bradyvercher** [comment]
No worries! Glad to hear that took care of it.
